services:

  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: borzik
      MYSQL_DATABASE: borzikdatabase
      MYSQL_USER: borzik
      MYSQL_PASSWORD: borzik
    ports:
      - "3306:3306"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]

  backend:
    container_name: backend
    image: 'backend'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
       mysql:
         condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/borzikdatabase
      SPRING_DATASOURCE_USERNAME: borzik
      SPRING_DATASOURCE_PASSWORD: borzik

  frontend:
      build:
        context: src/main/borzikfrontend
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      image: 'frontend'
      depends_on:
        - backend