server:
  port: 8081
logging.level.root: info
spring:
  application:
    name: borzik
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/borzikdatabase
    username: borzik
    password: borzik
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      platform: mysql

