server:
  port: 8081
logging.level.root: info
spring:
  application:
    name: borzik
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/borzikdatabase
    username: borzik
    password: borzik
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      mode: always
      platform: mysql
springdoc:
  api-docs:
    enabled: true
    path: /api
  swagger-ui:
    path: /swagger
    enabled: true
  show-actuator: true
